include:
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.0/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.0/gitlab-dom0.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.0/gitlab-vm.yml'

checks:pylint:
  stage: checks
  before_script:
    - pip3 install --quiet -r ci/requirements.txt
  script:
    - PYTHONPATH="test-packages:$PYTHONPATH" python3 -m pylint --rcfile=ci/pylintrc qubesmanager
