sudo: required
dist: trusty
language: python
python:
  - '3.5'
install:
 - sudo apt-get install python-qt4 pyqt4-dev-tools
 - pip install --quiet -r ci/requirements.txt
 - git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
script:
 - PYTHONPATH=test-packages pylint --rcfile=ci/pylintrc qubesmanager
 - ~/qubes-builder/scripts/travis-build
env:
 - DIST_DOM0=fc25 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
